# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: kineticdial
author: Patrick Brown
email: kineticdial@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  Patrick is a software engineer from New England. Today, he
  entertains himself by playing beer-league hockey and running
  Quasars, a link-aggregator for Astrophysics. He currently
  resides in the beautiful Greater Seattle Area.
baseurl: "" # the subpath of your site, e.g. /blog
show_excerpts: true
url: "https://kineticdial.github.io"

twitter_username: kineticdial
github_username:  kineticdial
medium_username: kineticdial
mastodon:
 - username: kineticdial
   instance: ruby.social

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
